name: grievease
description: A grievance management system
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  path_provider: ^2.1.3
  open_filex: ^4.7.0
  fl_chart: ^0.70.2
  http: ^1.1.2
  intl: ^0.20.2
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/GrievEase.jpg

